
server:
  port: 9001

#######################EUREKA#########################################################
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8001/eureka/
    #间隔到eureka拉去服务列表，默认30s，如果想要快速获取服务，建议设置少一些
    registry-fetch-interval-seconds: 10
  #  enabled: false

  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}  #注册实例ID生成规则
    #续约发送间隔，默认30s
    lease-renewal-interval-in-seconds: 30
    #续约持续时间，默认90s
    lease-expiration-duration-in-seconds: 60
spring:
  application:
    name: comsumer
  zipkin:
    base-url: http://localhost:9411
    #采样比例
  sleuth:
    sampler:
      rate: 1
######################################################################################
#######################FEIGN#########################################################
#使用 RequestInterceptor 和 FeignClient的configuration 效果一样。取其中一种即可,默认配置文件的RequestInterceptor优先级高
feign:
  #客户端配置压缩
#  compression:
#    request:
#      enabled: true
#      #达到2048b 压缩
#      min-request-size: 2048
#    response:
#      enabled: true

  client:
    config:
      #指定服务配置
      provider:
        request-interceptors: xyz.liangwh.feigncomsumer.config.MyBasicAuthRequestInterceptor
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
      #通用服务配置
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
    #属性配置比Java代码优先级高。也可通过配置设置java代码优先级高
    default-to-properties: false
    #############################Hystrix###################################################
  hystrix:
    enabled: true


  ######################################################################################

######################################################################################

#######################RIBBON#########################################################
#超时
ribbon:
  #连接超时时间(ms)
  ConnectTimeout: 30000
  #业务逻辑超时时间(ms)
  ReadTimeout: 30000

#重试
#同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetries: 1
#  #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1
#  #是否所有操作都重试
#  OkToRetryOnAllOperations: false


######################################################################################


